### ISSUE TITLE
package extensions overrided by pnpm-deduplicate

### ISSUE THREAD

**Issue by sahitpen1** [ocavue/pnpm-deduplicate#1] opened 2022-07-15 14:14 UTC
It seems like dependencies that are added in the `packageExtensions` in package.json are being overrided when this package is run. It feels like this package should be taking the `packageExtensions` into account and not overriding those.

**Comment by ocavue** [comment] 2022-07-17 02:27
@sahitpen1 Hi. You are correct that this library is not checking `packageExtensions` for now. However, I'm not sure in which scenario `pnpm-deduplicate` will override a dependency in `packageExtensions`. Could you provide a reproduce repository to me so that I can have a better understanding of the issue?

**Comment by ocavue** [comment] 2022-12-06 15:50
I'll close this issue for now since I don't know how to reproduce it. Feel free to open a new issue if someone is seeing the same problem.

**Closed as completed by ocavue** 2022-12-06 15:50 UTC
